# Generated by Django 4.2.29 on 2026-03-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization this user belongs to. Null for Super Admins.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ORG_ADMIN', 'Org Admin'), ('HO_USER', 'HO User'), ('RO_USER', 'RO User'), ('PIU_USER', 'PIU User'), ('PROJECT_USER', 'Project User')], default='PROJECT_USER', max_length=20, verbose_name='role'),
        ),
    ]
