# Generated by Django 4.2.29 on 2026-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_organization_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ORG_ADMIN', 'Org Admin'), ('HO_USER', 'HO User'), ('RO_USER', 'RO User'), ('PIU_USER', 'PIU User'), ('PROJECT_USER', 'Project User'), ('CONTRACTOR', 'Contractor')], default='PROJECT_USER', max_length=20, verbose_name='role'),
        ),
    ]
