# Generated by Django 4.2.29 on 2026-03-25 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ho_user',
            field=models.ForeignKey(blank=True, help_text='The HO user this user reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_ho_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='piu_user',
            field=models.ForeignKey(blank=True, help_text='The PIU user this user reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_piu_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='project_user',
            field=models.ForeignKey(blank=True, help_text='The Project user this user reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_project_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='ro_user',
            field=models.ForeignKey(blank=True, help_text='The RO user this user reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_ro_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
