# Generated by Django 4.2.29 on 2026-03-30 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('accounts', '0004_user_ho_user_user_piu_user_user_project_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, help_text='The dynamic org-specific role assigned to this user. Created by an Org Admin. Null for Super Admins and Org Admins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='roles.role'),
        ),
    ]
