# Generated by Django 5.2.13 on 2026-04-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_custom_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ORG_ADMIN', 'Org Admin'), ('HO_USER', 'HO User'), ('RO_USER', 'RO User'), ('PIU_USER', 'PIU User'), ('PROJECT_USER', 'Project User'), ('CONTRACTOR', 'Contractor'), ('UNASSIGNED', 'Unassigned')], default='PROJECT_USER', max_length=20, verbose_name='role'),
        ),
    ]
