# Generated by Django 4.2.29 on 2026-03-12 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='project name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('org_unit', models.ForeignKey(help_text="The org unit executing this project. Must be at the 'Project' hierarchy level.", on_delete=django.db.models.deletion.CASCADE, related_name='org_unit_projects', to='orgs.orgunit')),
                ('organization', models.ForeignKey(help_text='The organization this project belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='org_projects', to='orgs.organization')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'projects_project',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='idx_projects_org'), models.Index(fields=['org_unit'], name='idx_projects_orgunit')],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_project_org_name'),
        ),
    ]
