# Generated by Django 4.2.29 on 2026-03-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='org_unit',
            field=models.ForeignKey(blank=True, help_text="The org unit executing this project. Must be at the 'Project' hierarchy level.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_unit_projects', to='orgs.orgunit'),
        ),
    ]
