# Generated by Django 4.2.29 on 2026-03-25 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_alter_project_org_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ho_user',
            field=models.ForeignKey(blank=True, help_text='The assigned HO user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_ho', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='piu_user',
            field=models.ForeignKey(blank=True, help_text='The assigned PIU user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_piu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='ro_user',
            field=models.ForeignKey(blank=True, help_text='The assigned RO user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_ro', to=settings.AUTH_USER_MODEL),
        ),
    ]
