# Generated by Django 4.2.29 on 2026-03-25 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_project_ho_user_project_piu_user_project_ro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_user',
            field=models.ForeignKey(blank=True, help_text='The assigned Project user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_project_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
