# Generated by Django 4.2.29 on 2026-03-12 11:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. NH-58 Km 0.00-25.00', max_length=255, verbose_name='road name')),
                ('length', models.DecimalField(decimal_places=3, default=0, help_text='Road length in kilometres.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='length (km)')),
                ('geometry', models.JSONField(blank=True, default=None, help_text="GeoJSON LineString. Example: {'type': 'LineString', 'coordinates': [[lon, lat], ...]}", null=True, verbose_name='geometry')),
                ('road_type', models.CharField(blank=True, choices=[('NH', 'National Highway'), ('SH', 'State Highway'), ('MDR', 'Major District Road'), ('ODR', 'Other District Road'), ('VR', 'Village Road')], db_index=True, max_length=10, verbose_name='road type')),
                ('project', models.ForeignKey(help_text='The project this road belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='projects.project')),
            ],
            options={
                'verbose_name': 'road',
                'verbose_name_plural': 'roads',
                'db_table': 'roads_road',
                'ordering': ['project', 'name'],
                'indexes': [models.Index(fields=['project'], name='idx_road_project'), models.Index(fields=['road_type'], name='idx_road_type'), models.Index(fields=['project', 'road_type'], name='idx_road_project_type')],
            },
        ),
    ]
