# Generated by Django 4.2.29 on 2026-03-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='gpx_file',
            field=models.FileField(blank=True, help_text='Upload a GPX file for this road segment.', null=True, upload_to='gpx/', verbose_name='GPX File'),
        ),
    ]
