# Generated by Django 6.0.4 on 2026-05-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_road_gpx_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='json_data',
            field=models.JSONField(blank=True, default=None, help_text='Parsed content of the uploaded JSON file. Automatically populated when a JSON file is uploaded.', null=True, verbose_name='JSON Data'),
        ),
        migrations.AddField(
            model_name='road',
            name='json_file',
            field=models.FileField(blank=True, help_text='Upload a JSON file containing survey/analysis data for this road.', null=True, upload_to='road_json/', verbose_name='JSON Data File'),
        ),
    ]
