# Generated by Django 6.0.4 on 2026-05-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_add_json_file_to_road'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='road',
            name='json_file',
        ),
        migrations.AddField(
            model_name='road',
            name='furniture_json_data',
            field=models.JSONField(blank=True, default=None, help_text='Parsed content of the Furniture JSON file. Automatically populated when a furniture JSON file is uploaded.', null=True, verbose_name='Furniture JSON Data'),
        ),
        migrations.AddField(
            model_name='road',
            name='furniture_json_file',
            field=models.FileField(blank=True, help_text='Upload a JSON file containing road furniture / signage data.', null=True, upload_to='road_json/furniture/', verbose_name='Furniture JSON File'),
        ),
        migrations.AddField(
            model_name='road',
            name='pavement_json_data',
            field=models.JSONField(blank=True, default=None, help_text='Parsed content of the Pavement JSON file. Automatically populated when a pavement JSON file is uploaded.', null=True, verbose_name='Pavement JSON Data'),
        ),
        migrations.AddField(
            model_name='road',
            name='pavement_json_file',
            field=models.FileField(blank=True, help_text='Upload a JSON file containing pavement condition / analysis data.', null=True, upload_to='road_json/pavement/', verbose_name='Pavement JSON File'),
        ),
    ]
