# Generated by Django 6.0.4 on 2026-05-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_replace_json_with_furniture_pavement'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='survey_zip',
            field=models.FileField(blank=True, help_text='Upload a ZIP archive containing the complete survey folder (JSONs, GPX, etc.).', null=True, upload_to='road_surveys/zips/', verbose_name='Survey Folder (Zip)'),
        ),
    ]
