# Generated by Django 4.2.29 on 2026-03-12 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrgAccess',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('ho', 'HO'), ('ro', 'RO'), ('piu', 'PIU'), ('project', 'Project')], db_index=True, max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-disable access without deleting the record.', verbose_name='active')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The admin who created this assignment (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(help_text='The OrgUnit this user is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='orgs.orgunit')),
                ('user', models.ForeignKey(help_text='The user being granted access.', on_delete=django.db.models.deletion.CASCADE, related_name='org_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user org access',
                'verbose_name_plural': 'user org accesses',
                'db_table': 'access_userorgaccess',
                'ordering': ['user', 'org_unit'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_access_user_active'), models.Index(fields=['org_unit', 'role'], name='idx_access_unit_role'), models.Index(fields=['role'], name='idx_access_role')],
            },
        ),
        migrations.AddConstraint(
            model_name='userorgaccess',
            constraint=models.UniqueConstraint(fields=('user', 'org_unit'), name='uq_access_user_orgunit'),
        ),
    ]
