# Generated by Django 4.2.29 on 2026-03-12 07:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyLevel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level_name', models.CharField(help_text='Short label, e.g. HO, RO, PIU, Project', max_length=100, verbose_name='level name')),
                ('level_order', models.PositiveSmallIntegerField(help_text='1 = top of hierarchy, higher number = deeper level', verbose_name='level order')),
            ],
            options={
                'verbose_name': 'hierarchy level',
                'verbose_name_plural': 'hierarchy levels',
                'db_table': 'orgs_hierarchylevel',
                'ordering': ['organization', 'level_order'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='organization name')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='country')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'db_table': 'orgs_organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. HO Delhi, RO Lucknow, PIU Agra', max_length=255, verbose_name='unit name')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible key-value storage for extra attributes (budget code, state code, etc.).', verbose_name='metadata')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_units', to='orgs.hierarchylevel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_units', to='orgs.organization')),
                ('parent_unit', models.ForeignKey(blank=True, help_text='Direct parent unit. NULL means this is a root node.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='orgs.orgunit')),
            ],
            options={
                'verbose_name': 'org unit',
                'verbose_name_plural': 'org units',
                'db_table': 'orgs_orgunit',
                'ordering': ['organization', 'level__level_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['country'], name='idx_org_country'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='idx_org_active'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='uq_org_name_country'),
        ),
        migrations.AddField(
            model_name='hierarchylevel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_levels', to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='hierarchylevel',
            name='parent_level',
            field=models.ForeignKey(blank=True, help_text='The level immediately above this one. NULL for root levels.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_levels', to='orgs.hierarchylevel'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['parent_unit'], name='idx_orgunit_parent'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['organization'], name='idx_orgunit_org'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['level', 'is_active'], name='idx_orgunit_level_active'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['organization', 'is_active'], name='idx_orgunit_org_active'),
        ),
        migrations.AddConstraint(
            model_name='orgunit',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_orgunit_org_name'),
        ),
        migrations.AddIndex(
            model_name='hierarchylevel',
            index=models.Index(fields=['organization', 'level_order'], name='idx_hlevel_org_order'),
        ),
        migrations.AddConstraint(
            model_name='hierarchylevel',
            constraint=models.UniqueConstraint(fields=('organization', 'level_order'), name='uq_hlevel_org_order'),
        ),
        migrations.AddConstraint(
            model_name='hierarchylevel',
            constraint=models.UniqueConstraint(fields=('organization', 'level_name'), name='uq_hlevel_org_name'),
        ),
    ]
