# Generated by Django 4.2.29 on 2026-03-30 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100, verbose_name='role name')),
                ('hierarchy_level', models.PositiveSmallIntegerField(help_text='Lower number = higher authority. e.g. 1 is the top-most role.', verbose_name='hierarchy level')),
                ('has_supervisor_visibility', models.BooleanField(default=False, help_text='If enabled, users of this role can view all roles, all users (except Org Admin), and access all hierarchy dashboard filters.', verbose_name='supervisor visibility access')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='orgs.organization')),
                ('parent_role', models.ForeignKey(blank=True, help_text='The role that directly supervises this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='roles.role')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'roles_role',
                'ordering': ['organization', 'hierarchy_level', 'role_name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_key', models.CharField(max_length=50, verbose_name='permission key')),
                ('permission_value', models.BooleanField(default=False, verbose_name='permission value')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='roles.role')),
            ],
            options={
                'verbose_name': 'role permission',
                'verbose_name_plural': 'role permissions',
                'db_table': 'role_permissions',
            },
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission_key'), name='uq_role_permission_key'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'status'], name='idx_role_org_status'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'hierarchy_level'], name='idx_role_org_level'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'role_name'), name='uq_role_org_name'),
        ),
    ]
