# Generated by Django 4.2.29 on 2026-03-30 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['organization', 'is_supervisor_role', 'hierarchy_level', 'role_name'], 'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.RemoveIndex(
            model_name='role',
            name='idx_role_org_level',
        ),
        migrations.AddField(
            model_name='role',
            name='is_supervisor_role',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this is a special non-hierarchical Supervisor role. Users with this role gain org-wide visibility (view all roles, users, dashboards) but cannot create/delete roles or modify Org Admin permissions. hierarchy_level and parent_role are ignored for Supervisor roles.', verbose_name='supervisor role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='has_supervisor_visibility',
            field=models.BooleanField(default=False, help_text='Deprecated — use is_supervisor_role instead. If enabled, users can view all roles and users org-wide.', verbose_name='supervisor visibility access'),
        ),
        migrations.AlterField(
            model_name='role',
            name='hierarchy_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Lower number = higher authority. e.g. 1 is the top-most role. Leave blank for Supervisor roles.', null=True, verbose_name='hierarchy level'),
        ),
        migrations.AlterField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, help_text='The role that directly supervises this role. Leave blank for Supervisor roles.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='roles.role'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'is_supervisor_role'], name='idx_role_org_supervisor'),
        ),
    ]
